config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  get "dashboard", to: "home#dashboard"
  get 'home/index'
  root 'home#index'
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'
  resources :projects, path: :challenges do
    resources :enrollments, only: [:new, :create, :edit]
    get :accepted, :pending_review, :created, on: :collection
    resources :comments, module: :projects
  end

  resources :comments do
    resources :comments
  end
  resources :projects do
    member do
      put "like" => "projects#like"
      put "complete" => "projects#complete"
    end
  end
  resources :enrollments do
    member do
      put "complete" => "enrollment#complete"
    end
    get :incomplete, on: :collection
    member do
      patch :complete
      patch :uncomplete
    end
  end
  resources :tags, only: [:create, :index, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :projects
  has_many :enrollments
  validate :must_have_a_role, on: :update
  after_create :assign_default_role
  has_one_attached :avatar

  extend FriendlyId
  friendly_id :name, use: :slugged
  rolify
  acts_as_voter


  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:moderator)
      self.add_role(:user)
    else
      self.add_role(:user) if self.roles.blank?
    end
  end

  def to_s
    email
  end

  ransacker :name_case_insensitive, type: :string do
    arel_table[:name].lower
  end

  def join_project(project)
    self.enrollments.create(project: project)
  end

  has_many :invitations
  has_many :pending_invitations, -> { where confirmed: false }, class_name: 'Invitation', foreign_key: "friend_id"

  def friends
    friends_i_sent_invitation = Invitation.where(user_id: id, confirmed: true).pluck(:friend_id)
    friends_i_got_invitation = Invitation.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = friends_i_sent_invitation + friends_i_got_invitation
    User.where(id: ids)
  end

  def friend_with?(user)
    Invitation.confirmed_record?(id, user.id)
  end

  def send_invitation(user)
    invitations.create(friend_id: user.id)
  end


  private
    def must_have_a_role
      unless roles.any?
        errors.add(:roles, "must have at least one role")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show ]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
    @pagy, @users = pagy(@q.result(distinct: true).order(created_at: :desc))
    @popular_tags = Tag.all.where.not(project_tags_count: 0).order(project_tags_count: :desc).limit(10)
  end

  def show
    @enrollments = Enrollment.where(user: @user).all

  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to root_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :avatar, {role_ids: []})
  end
end

app/views/users/_friends.html.erb
  <h3><div class="fa fa-user-friends">
  </div> Friends of <strong> <%= @user.name %> </strong> </h3>
      <% @user.friends.each do |friend| %>
          <div class="card-group">
            <div class="card">
              <div class="card-body">
                <div class="row">
                  <div class="col-8">
                    <%= link_to friend.name, user_path(friend) %>
                  </div>
                  <div class="col">
                    <% if @user == current_user %>
                    <%= link_to 'Unfriend',
                    invitations_destroy_path(invitation_id: Invitation.find_invitation(@user.id, friend.id)), class: "btn btn-danger shiny"  %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>

app/views/users/_invites.html.erb
<% if @user == current_user && @user.pending_invitations.any? %>
  <h3> These people wants to be friends with you: </h3>
      <% @user.pending_invitations.each do |invitation| %>
        <div class="row">
          <div class="col-6">
            <%= link_to User.find(invitation.user_id).name, user_path(User.find(invitation.user_id))  %>
          </div>
          <div class="col">
            <%= link_to 'Accept Invitation',
            invitations_update_path(invitation_id: invitation.id) %>
            <%= link_to 'Reject Invitation',
            invitations_destroy_path(invitation_id: invitation.id) %>
          </div>
        </div>
    <% end %>
    <hr>
  <% end %>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-header">
    <%= image_tag user_avatar(user, 75), class: "rounded" %>
    <span class="h5">
      <div class="fa fa-user"></div>
      <%= link_to user.name, user_path(user) %><br>
    </span>
  <div class="card-body">
    <hr>
    <div class="fa fa-at"></div>
    <%=  user.email %><br>
    <div class="fa fa-clock"></div>
    Signed in <%= user.sign_in_count %> times <br>
    <div class="fa fa-calendar"></div>
    Last signed in <%= time_ago_in_words(user.current_sign_in_at) %> ago <br>
    <div class="fa fa-calendar-check"></div>
    Signed up <%= time_ago_in_words(user.created_at) %> ago <br>
    <div class="fa fa-user-friends"></div>
    Friends: <%= user.friends.count %> <br>

    <% if policy(user).edit? %>
      <hr>
        <% user.roles.each do |role| %>
          <div class="badge badge-info">
            <%= role.name %>
          </div>
        <% end %>
        <%= link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-yellow shiny' %>
      <% end %>
      <% if !Invitation.reacted?(current_user.id, user.id) && current_user != user %>
        <%= link_to 'Send Invitation', invitations_create_path(ids: {id1: current_user.id, id2: user.id}) %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/_userprojects.html.erb
<table class="table table-bordered table-striped table-sm table-hover">
  <thead>
    <tr>
      <th>
        Challenge
      </th>
      <th>
        Rating
      </th>
      <th>Complete?</th>
    </tr>
  </thead>
  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td>
          <%= link_to enrollment.project.name, project_path(enrollment.project) %>
        </td>
        <td>
          <%= enrollment.rating %>
        </td>
        <td>
          <%= enrollment.complete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/dashboard.html.erb
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
</style>
<body class="w3-theme-l5">


<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px">
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center">My Profile</h4>
         <p class="w3-center"><%= image_tag user_avatar(current_user, 100), class: "rounded" %></p>
         <br>

         <hr>
         <p><i class="fa fa-user fa-fw w3-margin-right w3-text-theme"></i> <%= link_to current_user.name, user_path(current_user) %></p>
         <p><i class="fa fa-at fa-fw w3-margin-right w3-text-theme"></i> <%= current_user.email %></p>
         <p><i class="fa fa-calendar-check fa-fw w3-margin-right w3-text-theme"></i> <%= current_user.created_at.strftime("%B %d, %Y") %></p>
        </div>
      </div>
      <br>

      <!-- Accordion -->
      <div class="w3-card w3-round">
        <div class="w3-white">
          <button onclick="myFunction('Demo1')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-trophy text-white fa-fw w3-margin-right"></i> Accepted Challenges</button>
          <div id="Demo1" class="w3-hide w3-container">
            <br>
            <% @enrollments.each do |enrollment| %>
              <p><%= link_to enrollment.project.name, project_path(enrollment.project) %></p>
              <hr>
            <% end %>
          </div>
          <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-users text-white fa-fw w3-margin-right"></i> My Friends</button>
            <div id="Demo3" class="w3-hide w3-container">
             <div class="w3-row-padding">
             <br>
               <% if @user.friends.any? %>
                   <% @user.friends.each do |friend| %>
                       <div class="row">
                         <div class="col">
                           <p><%= link_to friend.name, user_path(friend) %></p>
                         </div>
                         <div class="col-4">
                           <%= link_to 'Unfriend',
                           invitations_destroy_path(invitation_id: Invitation.find_invitation(@user.id, friend.id)), class: "btn btn-sm btn-danger shiny"  %>
                         </div>
                         <hr>
                       </div>
                   <% end %>
                   <% else %>
                     <p><%= link_to "Find a Friend", users_path %></p>
                 <% end %>
             </div>
          </div>
          <button onclick="myFunction('Demo2')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-check text-white fa-fw w3-margin-right"></i> Created Challenges</button>
          <div id="Demo2" class="w3-hide w3-container">
              <br>
              <% @created_projects.each do |project| %>
                <p><%= link_to project.name, project_path(project) %></p>
                <hr>
              <% end %>
          </div>
        </div>
      </div>
      <br>

      <!-- Interests -->
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          <p>Interests</p>
          <p>
            <span class="w3-tag w3-small w3-theme-d5">Life</span>
            <span class="w3-tag w3-small w3-theme-d4">Family</span>
            <span class="w3-tag w3-small w3-theme-d3">Cooking</span>
            <span class="w3-tag w3-small w3-theme-d2">Games</span>
            <span class="w3-tag w3-small w3-theme-d1">Friends</span>
            <span class="w3-tag w3-small w3-theme">Coding</span>
            <span class="w3-tag w3-small w3-theme-l1">Friends</span>
            <span class="w3-tag w3-small w3-theme-l2">Food</span>
            <span class="w3-tag w3-small w3-theme-l3">Fun</span>
            <span class="w3-tag w3-small w3-theme-l4">Art</span>
            <span class="w3-tag w3-small w3-theme-l5">Photos</span>
          </p>
        </div>
      </div>
      <br>

      <!-- Alert Box -->
      <div class="w3-container w3-display-container w3-round w3-theme-l4 w3-border w3-theme-border w3-margin-bottom w3-hide-small">
        <span onclick="this.parentElement.style.display='none'" class="w3-button w3-theme-l3 w3-display-topright">
          <i class="fa fa-exclamation"></i>
        </span>
        <p><strong>Hey!</strong></p>
        <p>You have been challenged! Find out who.</p>
      </div>

    <!-- End Left Column -->
    </div>

    <!-- Middle Column -->
    <div class="w3-col m7">

      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h5 class="w3-opacity">Issue a Challenge</h5>
              <%= render :partial => "projects/form", :locals => { :project => @project } %>

            </div>
          </div>
        </div>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="https://www.w3schools.com/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">30 min</span>
        <h4>Donate 10 unwanted items</h4><br>
        <hr class="w3-clear">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half">
              <img src="https://cdn.pixabay.com/photo/2016/07/17/20/19/t-shirt-1524677_960_720.jpg" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
            </div>
            <div class="w3-half">
              <img src="https://cdn.pixabay.com/photo/2017/08/28/21/54/toy-2691416_960_720.jpg" style="width:100%" alt="Nature" class="w3-margin-bottom">
          </div>
        </div>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button>
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="https://www.w3schools.com/w3images/avatar5.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">60 min</span>
        <h4>Cook a new dish</h4><br>
        <hr class="w3-clear">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button>
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button>
      </div>

      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="https://www.w3schools.com/w3images/avatar6.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">30</span>
        <h4>Send a real letter to friends or family</h4><br>
        <hr class="w3-clear">
        <p>Send a real letter to a friend or family member. Maybe you can remind them of a favorite memory or tell them how much you appreciate them.</p>
        <img src="https://cdn.pixabay.com/photo/2015/07/10/17/22/children-839789_960_720.jpg" style="width:100%" class="w3-margin-bottom">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button>
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button>
      </div>

    <!-- End Middle Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p></p>
          <p>Most Popular</p>
          <% @popular_project.each do |project| %>
          <img src="https://www.w3schools.com/w3images/forest.jpg" alt="Forest" style="width:100%;">
          <%= render "miniproject", project: project %>
          <% end %>
        </div>
      </div>
      <br>
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p></p>
          <p>Highest Rated</p>
          <% @best_project.each do |project| %>
          <img src="https://www.w3schools.com/w3images/forest.jpg" alt="Forest" style="width:100%;">
          <%= render "miniproject", project: project %>
          <% end %>
        </div>
      </div>
      <br>
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p></p>
          <p>Newest Challenge</p>
          <% @latest_project.each do |project| %>
          <img src="https://www.w3schools.com/w3images/forest.jpg" alt="Forest" style="width:100%;">
          <%= render "miniproject", project: project %>
          <% end %>
        </div>
      </div>
      <br>

    <% @user.pending_invitations.each do |invitation| %>
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p>Friend Request</p>
          <img src="https://www.w3schools.com/w3images/avatar6.png" alt="Avatar" style="width:50%"><br>
          <span><%= link_to User.find(invitation.user_id).name, user_path(User.find(invitation.user_id))  %></span>
          <div class="w3-row w3-opacity">
            <div class="w3-half">
              <button class="w3-button w3-block w3-green w3-section" title="Accept"><%= link_to 'Accept',
              invitations_update_path(invitation_id: invitation.id) %></button>
            </div>
            <div class="w3-half">
              <button class="w3-button w3-block w3-red w3-section" title="Decline"><%= link_to 'Reject',
              invitations_destroy_path(invitation_id: invitation.id) %></button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
      <br>

      <div class="w3-card w3-round w3-white w3-padding-16 w3-center">
        <p>Feedback</p>
      </div>
      <br>

      <div class="w3-card w3-round w3-white w3-padding-32 w3-center">
        <p><i class="fa fa-bug w3-xxlarge"></i></p>
      </div>
    </div>
  </div>
</div>
<br>

<script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-theme-d1";
  } else {
    x.className = x.className.replace("w3-show", "");
    x.previousElementSibling.className =
    x.previousElementSibling.className.replace(" w3-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

app/views/users/edit.html.erb
<div class="card">
  <div class="card-header">
    Editing roles for
    <%= @user.email %>
  </div>
  <div class="card-body">
    <%= simple_form_for @user do |f| %>
      <%= f.collection_check_boxes :role_ids, Role.all, :id, :name %>
      <%= f.error :roles, class: 'text-danger' %>
      <hr/>
      <%= f.button :submit, class: "btn shiny btn-success" %>
    <% end %>
  </div>

app/views/users/index.html.erb
<div class="form-inline">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :email_or_name_case_insensitive_cont, placeholder: 'Email or Name' %>
    <%= f.button :submit, class: "btn btn-sm shiny" do%>
    <div class="fa fa-search"></div>
    Search
    <% end %>
  <% end %>
  <div class="ml-2"></div>
  <%= link_to users_path, class: 'btn btn-sm shiny' do %>
    <div class="fa fa-sync-alt"></div>
    Reset
  <% end %>
</div>
<p></p>
<div class="card-columns">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user %>
  <% end %>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <%= render 'users/user', user: @user %>
    </div>
    <div class="col-4">
      <div class="card">
        <div class="card-header">
          <h3>Challenges Accepted</h3>
        </div>
        <div class="card-body">
          <%= render 'users/userprojects', user: @user %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-8">
      <div class="card-group">
        <div class="card card-body">
          <%= render 'users/friends', user: @user %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <%= render 'users/invites', user: @user %>
    </div>
  </div>
</div>