config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  get "dashboard", to: "home#dashboard"
  get 'home/index'
  root 'home#index'
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'
  resources :projects, path: :challenges do
    resources :enrollments, only: [:new, :create, :edit]
    get :accepted, :pending_review, :created, on: :collection
    resources :comments, module: :projects
  end

  resources :comments do
    resources :comments
  end
  resources :projects do
    member do
      put "like" => "projects#like"
      put "complete" => "projects#complete"
    end
  end
  resources :enrollments do
    member do
      put "complete" => "enrollment#complete"
    end
    get :incomplete, on: :collection
    member do
      patch :complete
      patch :uncomplete
    end
  end
  resources :tags, only: [:create, :index, :destroy]

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :project, counter_cache: true
  belongs_to :user, counter_cache: true

  validates :user, :project, presence: true

  validates_uniqueness_of :user_id, scope: :project_id  #user cant be subscribed to the same project twice
  validates_uniqueness_of :project_id, scope: :user_id  #user cant be subscribed to the same project twice

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }
  scope :complete, -> { where(complete: true) }
  scope :incomplete, -> { where(complete: false) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    user.to_s + " " + project.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      project.update_rating
    end
  end

  after_destroy do
    project.update_rating
  end

  protected


end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy complete uncomplete ]
  before_action :set_project, only: [:new, :create]

  # GET /enrollments or /enrollments.json
  def index
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
  end

  def incomplete
    @ransack_path = incomplete_enrollments_path
    @ransack_enrollments = Enrollment.incomplete.ransack(params[:enrollments_search], search_key: :enrollments_search)
    @pagy, @enrollments = pagy(@ransack_enrollments.result.includes(:user))
    render 'index'
  end

  def complete
    authorize @enrollment, :edit?
    @enrollment.update_attribute(:complete, true)
    redirect_to request.referrer, notice: "Congratulations on completing the challenge!"
  end

  def uncomplete
    authorize @enrollment, :edit?
    @enrollment.update_attribute(:complete, false)
    redirect_to request.referrer, notice: "Challenge marked as incomplete!"
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = current_user.join_project(@project)
    redirect_to project_path(@project), notice: "You accepted the challenge!"
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Thank you for rating this challenge." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: "You have left the challenge." }
      format.json { head :no_content }
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    def set_project
      @project = Project.friendly.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:rating, :review, :complete)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
  def complete_button(enrollment)
    if enrollment.complete?
      link_to 'Set to Incomplete', uncomplete_enrollment_path(enrollment), method: :patch, class: 'btn btn-danger'
    else
      link_to 'Mark as Complete', complete_enrollment_path(enrollment), method: :patch, class: 'btn btn-success'
    end
  end
end

app/views/enrollments/_enroll.html.erb
<%= form_tag project_enrollments_path(project) do %>
  <%= submit_tag "Join", class: 'btn shiny btn-success' %>
<% end %>

app/views/enrollments/_enrollment.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-user"></div>
    <%= link_to enrollment.user.name, user_path(enrollment.user) %> reviewed
    <div class="fa fa-trophy"></div>
    <%= link_to enrollment.project, project_path(enrollment.project) %>
    <%= time_ago_in_words(enrollment.updated_at) %> ago

  </div>
  <div class="card-body">
    <div class="text-warning fa fa-star"></div>
    <b>
      <%= enrollment.rating %>
    </b>
    <p></p>
  </div>
  <% if current_user %>
    <div class="card-footer">
      <div class="btn-group">
      <%= complete_button(enrollment) %>
        <% if policy(enrollment).edit? %>
          <%= button_to 'Edit Review', edit_enrollment_path(enrollment), method: :get, :class => "btn btn-shiny btn-info" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :rating, label: " ", collection: 1..5, as: :radio_buttons %>
  <%= f.input :complete, label: " ", as: :radio_buttons, collection: [[true, "Challenge complete!"], [false, "Still working on it..."]], label_method: :second, value_method: :first %><br>

  <%= f.button :submit, "Save", class: "btn btn-info shiny" %>

<% end %>

app/views/enrollments/edit.html.erb
<div class="card">
  <div class="card-body">
  <h3><div class="fa fa-star"></div> Rate this Challenge</h3>
  <%= render 'form', enrollment: @enrollment %>
<hr>
  <div class="btn-group" role="group">
    <%= button_to 'Cancel', @enrollment, :class => "btn shiny btn-success" %>
  </div>
  <p></p>
  </div>
</div>

app/views/enrollments/index.html.erb
<%= search_form_for @q do |f| %>
  <%= f.search_field :user_email_cont, placeholder: 'User Email' %>
  <%= f.search_field :project_name_cont, placeholder: 'Challenge' %>
  <%= f.search_field :rating_eq, placeholder: 'Rating' %>
<br>
  <%= f.button :submit, class: "btn btn-sm shiny" do%>
    <div class="fa fa-search"></div>
    Search
  <% end %>
  <%= link_to enrollments_path, class: 'btn btn-sm shiny' do %>
  <div class="fa fa-sync-alt"></div>
  Reset
  <% end %>
<% end %>
<p></p>
<table class="table table-bordered table-striped table-sm table-hover">
  <thead>
    <tr>
      <th><%= sort_link(@q, :id) %></th>
      <th>
        <%= sort_link(@q, :user_email) %>
      </th>
      <th>
        <%= sort_link(@q, :created_at) %>
      </th>
      <th>
        <%= sort_link(@q, :project_name) %>
      </th>
      <th>
        <%= sort_link(@q, :updated_at) %>
      </th>
      <th>
        <%= sort_link(@q, :rating) %>
      </th>
      <th>Complete?</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td>
          <%= enrollment.id %>
        </td>
        <td>
          <%= link_to enrollment.user.email, user_path(enrollment.user) %>
        </td>
        <td>
          <%= enrollment.created_at.strftime("%d/%b/%Y, %H:%M") %>
        </td>
        <td>
          <%= link_to enrollment.project.name, project_path(enrollment.project) %>
        </td>
        <td>
          <% if enrollment.rating.present? %>
            <%= enrollment.updated_at.strftime("%d/%b/%Y, %H:%M") %>
          <% end %>
        </td>
        <td>
          <%= enrollment.rating %>
        </td>
        <td>
          <%= enrollment.complete %>
        </td>
        <td>
          <%= link_to 'Add Review', edit_enrollment_path(enrollment) %>
        </td>
        <td>
          <%= link_to 'Leave Challenge', enrollment, method: :delete, data: { confirm: 'Are you sure you want to leave this challenge?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/enrollments/new.html.erb
<div class="card">
  <div class="card-header">
    <h3>
      <div class="fa fa-graduation-cap"></div>
      <%= link_to @project.name, project_path(@project) %>
      <hr/>
      <div class="fa fa-lock-open"></div>
      Accept the Challenge
    </h3>
  </div>
  <div class="card-body">
    <%= form_tag project_enrollments_path(@project) do %>
      <%= submit_tag "Join", class: 'btn btn-lg btn-success' %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= button_to 'Back', project_path(@project),  :class => "btn shiny btn-yellow" %>
  </div>
</div>

app/views/enrollments/show.html.erb
<%= render 'enrollments/enrollment', enrollment: @enrollment %>
<p></p>
<div class="btn-group" role="group">
  <%= button_to 'Back', enrollments_path, method: :get, :class => "btn shiny btn-yellow" %>
</div>