config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  get "dashboard", to: "home#dashboard"
  get 'home/index'
  root 'home#index'
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'
  resources :projects, path: :challenges do
    resources :enrollments, only: [:new, :create, :edit]
    get :accepted, :pending_review, :created, on: :collection
    resources :comments, module: :projects
  end

  resources :comments do
    resources :comments
  end
  resources :projects do
    member do
      put "like" => "projects#like"
      put "complete" => "projects#complete"
    end
  end
  resources :enrollments do
    member do
      put "complete" => "enrollment#complete"
    end
    get :incomplete, on: :collection
    member do
      patch :complete
      patch :uncomplete
    end
  end
  resources :tags, only: [:create, :index, :destroy]

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fbeec1">
  <a class="navbar-brand" href="/">Challenger</a>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>
        <li class="nav-item dropdown <%= 'active font-weight-bold' if current_page?(users_path) %>">
          <a class="nav-link dropdown-toggle" href="/users" id="usersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="fa fa-user"></div>
              Users
          </a>
          <div class="dropdown-menu" aria-labelledby="usersDropdown">
            <%= link_to users_path, class: "dropdown-item" do %>
              <div class="fa fa-users"></div>
              <b>All Users</b>
              <div class="badge badge-success">
                <%= User.count %>
              </div>
            <% end %>
            <%= link_to user_path(current_user), class: "dropdown-item" do %>
              <div class="fa fa-user-friends"></div>
              <b>Friends</b>
              <div class="badge badge-success">
                <%= current_user.friends.count %>
              </div>
            <% end %>
            <%= link_to user_path(current_user), class: "dropdown-item" do %>
              <div class="fa fa-user"></div>
              <b>My Profile</b>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown <%= 'active font-weight-bold' if current_page?(projects_path) %>">
          <a class="nav-link dropdown-toggle" href="/users" id="challengesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="fa fa-trophy"></div>
              Challenges
          </a>
          <div class="dropdown-menu dropdown-menu-left" aria-labelledby="challengesDropdown">
            <%= link_to projects_path, class: "dropdown-item" do %>
              <div class="fa fa-trophy"></div>
              <b>All Challenges</b>
              <div class="badge badge-success">
                <%= Project.count %>
              </div>
            <% end %>
            <%= link_to new_project_path, class: "dropdown-item" do %>
              <div class="fa fa-plus"></div>
              <b> Issue a Challenge</b>
            <% end %>
            <%= link_to created_projects_path, class: "dropdown-item" do %>
              <div class="fa fa-user-shield"></div>
              <b> Challenges Issued</b>
              <div class="badge badge-success">
                <%= current_user.projects_count %>
              </div>
            <% end %>
            <%= link_to enrollments_path, class: "dropdown-item" do %>
              <div class="fa fa-lock-open"></div>
              <b>Challenges Accepted</b>
              <div class="badge badge-success">
                <%= current_user.enrollments_count %>
              </div>
            <% end %>
            <%= link_to pending_review_projects_path, class: "dropdown-item" do %>
              <div class="fa fa-star"></div>
              <b>Pending Review</b>
            <% end %>
          </div>
        </li>
        <li class="nav-item <%= 'active font-weight-bold' if current_page?(tags_path) %>">
          <%= link_to tags_path, class: "nav-link" do %>
          <div class="fa fa-tags"></div>
          Interests
        </li>
        <% end %>
      </ul>
      <div class="form-inline my-2 my-lg-0">
        <%= search_form_for @ransack_projects, as: :projects_search, url: projects_path do |f| %>
        <div class="input-group">
          <%= f.search_field :name_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a challenge', :autocomplete => :off %>
          <span class="input-group-append">
            <button class="btn btn-primary btn-sm shiny" type="submit">
              <span aria-hidden="true" class="fa fa-search"></span>
            </button>
          </span>
        </div>
      <% end %>
      </div>
      <ul class="navbar-nav mr-right">
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <%= image_tag user_avatar(current_user, 20), class: "rounded-circle" %>
              <%= current_user.name %>
            </b>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to dashboard_path, class: "dropdown-item" do %>
              <div class="fa fa-solar-panel"></div>
              <b>My dashboard</b>
            <% end %>
            <%= link_to user_path(current_user), class: "dropdown-item" do %>
              <div class="fa fa-user"></div>
              <b>My profile</b>
            <% end %>
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, class: "alert alert-#{['success','notice'].include?(key) ? 'success' : 'danger'}" do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= value %>
      <% end %>
    <% end %>
    <div class="container" style="max-width:1400px;margin-top:20px">
      <%= yield %>
    </div>
 </body>
</html>